name: RPM build
on: [push]
env:
  ARTIFACTORY_URL: https://rpmb.jfrog.io
  BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
  BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
  OS7: 7.9.2009
  OS8: 8.3.2011
  OS7TAG: 7.9.2009
  OS8TAG: 8.3.2011
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - compose-file: docker-compose.yml
            repo: custom
            build: centos7build
            uploader: centos7bintray
          - compose-file: docker-compose.yml
            repo: custom
            build: centos8build
            uploader: centos8bintray
    env:
      BUILD_COMPOSE_FILE: ${{ matrix.compose-file }}
      BINTRAY_REPO: ${{ matrix.repo }}
      BUILD: ${{ matrix.build }}
      UPLOADER: ${{ matrix.uploader }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: docker-compose -f $BUILD_COMPOSE_FILE build --no-cache $BUILD
      - run: docker-compose -f $BUILD_COMPOSE_FILE up --exit-code-from $BUILD $BUILD
      - run: docker-compose -f rpmbuild/docker-compose.bintray.yml pull $UPLOADER
      - run: docker-compose -f rpmbuild/docker-compose.bintray.yml run --rm -e BINTRAY_USER=$BINTRAY_USER -e BINTRAY_API_KEY=$BINTRAY_API_KEY -e BINTRAY_REPO=$BINTRAY_REPO -e ARTIFACTORY_URL=$ARTIFACTORY_URL $UPLOADER
